// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ValueAdded
arma::mat ValueAdded(List All);
RcppExport SEXP _mvam_ValueAdded(SEXP AllSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type All(AllSEXP);
    rcpp_result_gen = Rcpp::wrap(ValueAdded(All));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_mvam_ValueAdded", (DL_FUNC) &_mvam_ValueAdded, 1},
    {"_rcpp_module_boot_mod", (DL_FUNC) &_rcpp_module_boot_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_mvam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
