# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testfunc <- function(x) {
    .Call(`_mvam_testfunc`, x)
}

ValueAdded <- function(All) {
    .Call(`_mvam_ValueAdded`, All)
}

